name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/icon-kucing-1.png
    - assets/page-1/images/vaadin-line-bar-chart.png
    - assets/page-1/images/vaadin-line-bar-chart-LQy.png
    - assets/page-1/images/ei-arrow-left.png
    - assets/page-1/images/guidance-calendar.png
    - assets/page-1/images/vaadin-line-bar-chart-H53.png
    - assets/page-1/images/guidance-calendar-BxM.png
    - assets/page-1/images/icon-kucing-1-kFs.png
    - assets/page-1/images/arcticons-news.png
    - assets/page-1/images/zondicons-pause-outline.png
    - assets/page-1/images/vaadin-line-bar-chart-kLy.png
    - assets/page-1/images/typcn-delete.png
    - assets/page-1/images/icon-kucing-2.png
    - assets/page-1/images/icon-kucing-1-bkD.png
    - assets/page-1/images/icon-kucing-1-E6d.png
    - assets/page-1/images/menu-button.png
    - assets/page-1/images/guidance-calendar-DJR.png
    - assets/page-1/images/typcn-delete-qwo.png
    - assets/page-1/images/icon-kucing-1-wMB.png
    - assets/page-1/images/vaadin-line-bar-chart-Hey.png
    - assets/page-1/images/vaadin-line-bar-chart-S25.png
    - assets/page-1/images/mdi-user-outline.png
    - assets/page-1/images/vaadin-line-bar-chart-TQM.png
    - assets/page-1/images/mdi-password-outline.png
    - assets/page-1/images/ic-outline-home.png
    - assets/page-1/images/arcticons-news-3o7.png
    - assets/page-1/images/material-symbols-water-full-outline.png
    - assets/page-1/images/ic-outline-settings.png
    - assets/page-1/images/icon-kucing-1-z2d.png
    - assets/page-1/images/icon-kucing-1-xp1.png
    - assets/page-1/images/carbon-stop-outline.png
    - assets/page-1/images/icon-kucing-1-YnD.png
    - assets/page-1/images/vaadin-line-bar-chart-xG9.png
    - assets/page-1/images/vaadin-line-bar-chart-uBP.png
    - assets/page-1/images/formkit-add.png
    - assets/page-1/images/fe-login.png
    - assets/page-1/images/streamline-food-pizza-drink-cook-fast-cooking-nutrition-pizza-food.png
    - assets/page-1/images/menu-button-yNq.png
    - assets/page-1/images/icon-kucing-1-JAD.png
    - assets/page-1/images/bi-toggle-on.png
    - assets/page-1/images/vaadin-line-bar-chart-3A9.png
    - assets/page-1/images/arcticons-news-me9.png
    - assets/page-1/images/vaadin-line-bar-chart-re5.png
    - assets/page-1/images/arcticons-news-1Ym.png
    - assets/page-1/images/icon-kucing-1-d7P.png
    - assets/page-1/images/ri-add-fill.png
    - assets/page-1/images/vaadin-line-bar-chart-zam.png
    - assets/page-1/images/vaadin-line-bar-chart-aHw.png
    - assets/page-1/images/menu-button-AHw.png
    - assets/page-1/images/vaadin-line-bar-chart-ULy.png
    - assets/page-1/images/mdi-food-outline.png
    - assets/page-1/images/mdi-edit-circle.png
    - assets/page-1/images/menu-button-cLR.png
    - assets/page-1/images/vaadin-line-bar-chart-5jo.png
    - assets/page-1/images/mdi-content-save-plus-outline.png
    - assets/page-1/images/fluent-ios-arrow-24-regular.png
    - assets/page-1/images/vaadin-line-bar-chart-GmP.png
    - assets/page-1/images/vaadin-line-bar-chart-zxH.png
    - assets/page-1/images/mdi-content-save-plus-outline-hrh.png
    - assets/page-1/images/fluent-ios-arrow-24-regular-WbB.png
    - assets/page-1/images/vaadin-line-bar-chart-DHB.png
    - assets/page-1/images/typcn-delete-wCM.png
    - assets/page-1/images/arcticons-news-bi9.png
    - assets/page-1/images/ri-add-fill-21P.png
    - assets/page-1/images/fluent-ios-arrow-24-regular-rr5.png
    - assets/page-1/images/material-symbols-water-full-outline-5dB.png
    - assets/page-1/images/bi-toggle-on-Rh3.png
    - assets/page-1/images/ic-outline-settings-369.png
    - assets/page-1/images/iconamoon-arrow-right-2.png
    - assets/page-1/images/typcn-delete-wbP.png
    - assets/page-1/images/menu-button-BAH.png
    - assets/page-1/images/streamline-food-pizza-drink-cook-fast-cooking-nutrition-pizza-food-JJm.png
    - assets/page-1/images/guidance-calendar-oDT.png
    - assets/page-1/images/clarity-clock-line.png
    - assets/page-1/images/mdi-edit-circle-9cM.png
    - assets/page-1/images/mdi-edit-circle-WC1.png
    - assets/page-1/images/iconamoon-arrow-right-2-Nmo.png
    - assets/page-1/images/ri-add-fill-6p1.png
    - assets/page-1/images/formkit-add-tnD.png
    - assets/page-1/images/mdi-edit-circle-qhT.png
    - assets/page-1/images/fluent-ios-arrow-24-regular-vZf.png
    - assets/page-1/images/menu-button-rPK.png
    - assets/page-1/images/material-symbols-edit-outline.png
    - assets/page-1/images/ic-outline-settings-Pa1.png
    - assets/page-1/images/vaadin-line-bar-chart-8Xb.png
    - assets/page-1/images/iconamoon-arrow-right-2-sRs.png
    - assets/page-1/images/ic-baseline-arrow-circle-right.png
    - assets/page-1/images/auto-group-xt4j.png
    - assets/page-1/images/vaadin-line-bar-chart-HW1.png
    - assets/page-1/images/fluent-ios-arrow-24-regular-MoF.png
    - assets/page-1/images/ri-add-fill-xKj.png
    - assets/page-1/images/vaadin-line-bar-chart-DmB.png
    - assets/page-1/images/mdi-content-save-plus-outline-qa9.png
    - assets/page-1/images/ei-arrow-left-kh7.png
    - assets/page-1/images/menu-button-7x5.png
    - assets/page-1/images/ic-outline-settings-r4y.png
    - assets/page-1/images/material-symbols-edit-outline-njK.png
    - assets/page-1/images/fluent-ios-arrow-24-regular-pzd.png
    - assets/page-1/images/icon-kucing-2-83s.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
