name: tugas_akhir
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.5
  firebase_storage:
  convex_bottom_bar: ^3.0.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  mqtt_client: ^10.0.0
  flutter_svg: ^2.0.7
  maps_launcher: ^2.0.1
  syncfusion_flutter_datepicker: ^20.1.51


dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_analytics: ^10.4.5
  flutter_lints: ^2.0.0
  google_fonts: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900